apiVersion: v1
kind: Service
metadata:
  name: ignite
  namespace: ignite-test
spec:
  type: NodePort
  selector:
    app: ignitetest
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31007